version: '3.8'

services:
  app:
    build:
      context: ".."
      dockerfile: Dockerfile
    container_name: akash-app
    restart: always
    working_dir: /var/www/
    volumes:
      - ../:/var/www
      - /var/www/vendor
    depends_on:
      - db
  nginx:
    image: nginx:1.19-alpine
    container_name: akash-nginx
    restart: always
    ports:
      - "8010:80"
    volumes:
      - ../:/var/www
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - app
  db:
    container_name: akash-db
    image: mysql:8.0
    volumes:
      - mysql:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - "4406:3306"
    healthcheck:
      test:
        - CMD
        - mysqladmin
        - ping
        - '-p${DB_PASSWORD}'
      retries: 3
      timeout: 5s

volumes:
  mysql:
